version: '3.4'

services:
  api:
    build:
      context: .
      target: development
    depends_on:
      - postgres
    volumes:
      - .:/user/app/src
      - /usr/src/app/node_modules
    ports:
      -  4000:4000
    command: npm run dev

  postgres:  
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testing
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: